### ISSUE TITLE
jshint in dependencies

### ISSUE THREAD

**Issue by skoranga** [krakenjs/karka#3]
Looks like `jshint` is part of both dependencies and devDependencies in package.json. Checked not used in non-test code. I think safe to get rid of https://github.com/krakenjs/karka/blob/master/package.json#L22

**Comment by pvenkatakrishnan** [comment]
yep. Pr ?

**Comment by pvenkatakrishnan** [comment]
https://github.com/krakenjs/karka/pull/4

**Comment by skoranga** [comment]
:+1:  for prompt response.
